// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shruhfetokzwxaexdxyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNocnVoZmV0b2t6d3hhZXhkeHl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MzQ3MzMsImV4cCI6MjA2MTMxMDczM30.kViibIYzgB_HRJf4R8BOUE382WZiQdmd-bk9i1Uf0fQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);